//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KNearestNeighbor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KNearestNeighbor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;
        ///&lt;ol&gt;text1&lt;/ol&gt;
        ///&lt;ol&gt;text2&lt;/ol&gt;
        ///&lt;/li&gt;
        ///
        ///&lt;li&gt;
        ///&lt;ol&gt;text3&lt;/ol&gt;
        ///&lt;ol&gt;text4&lt;/ol&gt;
        ///&lt;/li&gt;
        ///
        ///&lt;strong&gt;this is some text here&lt;/strong&gt;
        ///&lt;em&gt;this is some italic text&lt;/em&gt;
        ///&lt;li&gt;
        ///&lt;ul&gt;text1&lt;/ul&gt;
        ///&lt;ul&gt;text2&lt;/ul&gt;
        ///&lt;/li&gt;
        ///
        ///This is some text describing what the KNN algorithm is all about. It is also here to see if we will run off the side of the program or will we wrap around?
        ///
        ///&lt;h2&gt;Here is some&lt;/h2&gt;.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;u&gt;Step 1:&lt;/u&gt; Select the training data via the Browse button.
        ///
        ///&lt;u&gt;Step 2:&lt;/u&gt; Verify the number of attributes and training data are correct.
        ///
        ///&lt;u&gt;Step 3:&lt;/u&gt; Enter your input data (continuous only).
        ///
        ///&lt;u&gt;Step 4:&lt;/u&gt; Enter in a k value (0 &lt; k &lt;= trainingData.Count())
        ///
        ///&lt;u&gt;Step 5:&lt;/u&gt; Click the Next button to compute the class of your data point..
        /// </summary>
        internal static string inputdatainstructions {
            get {
                return ResourceManager.GetString("inputdatainstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] knnHelp {
            get {
                object obj = ResourceManager.GetObject("knnHelp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon openofficeorg_math_2ze_icon {
            get {
                object obj = ResourceManager.GetObject("openofficeorg_math_2ze_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap orange_light_main_top {
            get {
                object obj = ResourceManager.GetObject("orange-light-main-top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap orange_light_top {
            get {
                object obj = ResourceManager.GetObject("orange_light_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
